spring:
  boot:
    admin:
      client:
        url: http://localhost:8089
  application:
    name: discovery-server
#  security:
#    basic:
#      enabled: true
#    user:
#      name: adm
#      password: adm

server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: ./logs/${spring.application.name:${random.value}}.log